## Numpy Continuation:

### Iteration of array:


In [1]:
l = [1,2,3,45]
l

[1, 2, 3, 45]

In [2]:
for i in l:    ### looping directly by the elements
    print(i)
    

1
2
3
45


In [4]:
for i in range(len(l)):   ### looping using index value
    print(l[i])

1
2
3
45


In [7]:
### 1-d array looping:

import numpy as np

a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [8]:
for i in a:
    print(i,end = " ")

1 2 3 4 5 6 

In [10]:
### 2-d array:

b = a.reshape(2,3)
b

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
for i in b:    ### i holds row 
    for j in i:   ### j holds row elements
        print(j,end = " ")

1 2 3 4 5 6 

In [13]:
#### 3-d array looping:

c = a.reshape(2,3,1)
c

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [15]:
for i in c:   ### i holds 2-d array
    for j in i:   ### j holds row
        for k in j:   ### k holds element
            print(k,end = " ")
            

1 2 3 4 5 6 

In [20]:
### keyword for iterating the array:
###np.nditer

for i in np.nditer(c):
    print(i,end = " ")

1 2 3 4 5 6 

###  Joining of arrays:



In [23]:
### 1-d array:

a = np.arange(1,10)
b = np.arange(11,20)
c = np.concatenate((a,b))
c

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [24]:
### 2-d array:

c = a.reshape(3,3)
d = b.reshape(3,3)
e = np.concatenate((c,d))
e

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [25]:
#### 2-d array:

f = a.reshape(3,1,3)
g = b.reshape(3,1,3)
h = np.concatenate((f,g))
h

array([[[ 1,  2,  3]],

       [[ 4,  5,  6]],

       [[ 7,  8,  9]],

       [[11, 12, 13]],

       [[14, 15, 16]],

       [[17, 18, 19]]])

* To concatenate any two arrays the shape should be same and the dimensions should be same

### Stastical and Math operations on arrays:

In [32]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
np.min(c)    ### minimum value

1

In [35]:
np.max(c)  ### maximum value

9

In [38]:
c.max()

9

In [41]:
c.argmin()   ### min value index

0

In [42]:
c.argmax()   ### max value index

8

In [45]:
c.mean()   ### mean of the array elements


5.0

In [47]:
np.median(c)    ### median of the array elements

5.0

In [48]:
np.var(c)   ### variance of the array elements

6.666666666666667

In [49]:
np.average(c) ### average of the array elements

5.0

In [50]:
np.std(c)   ### standard deviation of the array elements

2.581988897471611

In [51]:
np.sum(c)   ### sum of all the array elements

45

In [52]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
np.sum(c,1)   ### sum of the row elements

array([ 6, 15, 24])

In [55]:
np.sum(c,0)   ### sum of the column elements

array([12, 15, 18])

* 1  ------ row wise
* 0  ------ column wise

In [56]:
np.argmax(c,1)

array([2, 2, 2], dtype=int64)

In [57]:
np.argmin(c,1)

array([0, 0, 0], dtype=int64)

In [58]:
np.argmax(c,0)

array([2, 2, 2], dtype=int64)

##### Stacking : 
      arranging /organising in an appropriate way

* vertical stacking
* Horizantal stacking

In [59]:
np.hstack(c)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
np.vstack((c,d))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [62]:
np.sqrt(c)    ### square root of the array elements

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [63]:
np.exp(c)    ### exponential of the array elements

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [64]:
np.sin(c)   ### sine of the array elements

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ],
       [ 0.6569866 ,  0.98935825,  0.41211849]])

In [65]:
np.cos(c)  ### cosine of the array elements

array([[ 0.54030231, -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029],
       [ 0.75390225, -0.14550003, -0.91113026]])

In [66]:
np.tan(c)  ### tan of the array elements

array([[ 1.55740772, -2.18503986, -0.14254654],
       [ 1.15782128, -3.38051501, -0.29100619],
       [ 0.87144798, -6.79971146, -0.45231566]])

In [67]:
np.log(c)  ### logarithmic values of the array elements

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [69]:
np.log2(c)    ### log values with base 2

array([[0.        , 1.        , 1.5849625 ],
       [2.        , 2.32192809, 2.5849625 ],
       [2.80735492, 3.        , 3.169925  ]])

In [71]:
np.log10(c)   ### log values with base 10

array([[0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125],
       [0.84509804, 0.90308999, 0.95424251]])

In [73]:
np.remainder(c,3)   ### remainder of the each array element

array([[1, 2, 0],
       [1, 2, 0],
       [1, 2, 0]], dtype=int32)

In [74]:
np.degrees(c)   ### degrees of the array elements

array([[ 57.29577951, 114.59155903, 171.88733854],
       [229.18311805, 286.47889757, 343.77467708],
       [401.07045659, 458.3662361 , 515.66201562]])

In [75]:
np.diff(c)

array([[1, 1],
       [1, 1],
       [1, 1]])

In [79]:
np.ediff1d(c)  ### converts the array into 1-d and calculates the consecutive difference of each element

array([1, 1, 1, 1, 1, 1, 1, 1])

In [81]:
np.i0(c)  ### bessel function

array([[   1,    2,    4],
       [  11,   27,   67],
       [ 168,  427, 1093]])

In [83]:
np.mod(c,4) ### Modulous of the each element in the array.

array([[1, 2, 3],
       [0, 1, 2],
       [3, 0, 1]], dtype=int32)

In [85]:
np.power(c,2)  ### Power

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]], dtype=int32)

In [87]:
np.reciprocal(c,dtype = float)

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667],
       [0.14285714, 0.125     , 0.11111111]])

In [89]:
np.multiply(c,2)   ### product of the array elements with a given number

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [90]:
np.divide(c,6)    ### divide

array([[0.16666667, 0.33333333, 0.5       ],
       [0.66666667, 0.83333333, 1.        ],
       [1.16666667, 1.33333333, 1.5       ]])

In [91]:
a = np.array([1+2j,2+3j,10+4j])

a

array([ 1.+2.j,  2.+3.j, 10.+4.j])

In [96]:
np.real(a)    ### real values of the given array elements

array([ 1.,  2., 10.])

In [94]:
np.imag(a)   ### imaginary values of the given array elements

array([2., 3., 4.])

#### Ravel and Flatten:

* Ravel :  Ravel is a function used to create copy of the original array.When any changes made in the duplicate array those will also applied in the original array.
* Flatten: Flatten is a function used to create copy of the original array.When any changes made in the duplicate array those won't be applied in the original array.


In [99]:
original = np.arange(1,10)
original

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [101]:
copy = original.ravel()
copy

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [102]:
copy[0] = 11

In [103]:
copy

array([11,  2,  3,  4,  5,  6,  7,  8,  9])

In [104]:
original

array([11,  2,  3,  4,  5,  6,  7,  8,  9])

In [105]:
copy1 = original.flatten()

In [106]:
copy1

array([11,  2,  3,  4,  5,  6,  7,  8,  9])

In [107]:
copy1[0] = 1

In [108]:
copy1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [109]:
original

array([11,  2,  3,  4,  5,  6,  7,  8,  9])

### Random Methods:

In [118]:
np.random.randint(150)   ###integer value within a given range

125

In [124]:
np.random.rand()  ### float value within 0 and 1 range

0.4600995699671174

In [126]:
np.random.randint(100,size = (20))  ## 1-d array with defined number of elements in the given range

array([36, 73, 85, 38, 18, 62, 34, 34, 71, 60,  0,  2, 40, 31, 94, 51, 75,
       85, 47, 45])

In [127]:
np.random.randint(100,size = (3,4))  ### 2-d array

array([[57, 18, 33, 50],
       [26,  0,  9,  2],
       [24, 74, 64, 46]])

In [128]:
np.random.randint(100,size = (2,3,4))   ### 3-d array

array([[[16, 30, 16, 25],
        [11, 33, 38, 92],
        [90, 16, 56, 64]],

       [[60, 23,  3, 99],
        [ 5, 80, 31, 49],
        [74, 77, 73, 50]]])

In [137]:
np.random.choice([14,22,1,5,11,12,24,7])    


24

In [138]:
np.random.choice([14,22,1,5,11,12,24,7],size = (3,3))   ### 2-d array

array([[14,  7,  1],
       [24,  1, 22],
       [ 1,  5, 14]])

In [140]:
np.random.choice([14,22,1,5,11,12,24,7],size = (2,3,3))   ## 3-d array

array([[[12,  1,  5],
        [14,  7,  5],
        [22, 11,  7]],

       [[ 5, 14, 11],
        [ 7, 22,  1],
        [14, 12, 14]]])

In [143]:
np.random.choice([14,22,1,5,11,12,24,7],p = [0.3,0.1,0.3,0.1,0.2,0,0,0],size = (3,4))

array([[22, 14, 14,  5],
       [11, 11, 14, 11],
       [11,  1, 11,  1]])

In [153]:
np.random.shuffle(c)  ### places of the elements in the array will be changed

In [154]:
c

array([[7, 8, 9],
       [1, 2, 3],
       [4, 5, 6]])

In [156]:
np.random.randn(10)  ### positive and negative values in defined number

array([ 0.7586107 , -0.5183539 ,  0.61700774,  1.06307763, -0.36140815,
       -0.47459125, -1.80349429,  1.44859272, -0.31072442, -0.76324773])

In [159]:
np.random.normal()   ### normal distribution

1.0702163952562913

In [161]:
np.random.binomial(10,p=[0.1],size =(4))   ### binomial distribution

array([1, 3, 1, 1])

#### Array Filtering:

In [163]:
a = np.array([10,14,22,7,12,95,20])
b = [False,True,True,True,True,False,False]
c = a[b]
c

array([14, 22,  7, 12])

In [165]:
### print the values which greater than 20
b = []
for i in a:
    if i>20:
        b.append(True)
    else:
        b.append(False)
c = a[b]
c

array([22, 95])

In [167]:
d = a > 20
e = a[d]

In [168]:
e

array([22, 95])

In [173]:
a.reshape(7,1)

array([[10],
       [14],
       [22],
       [ 7],
       [12],
       [95],
       [20]])

In [174]:
 a.T   ### transpose

array([10, 14, 22,  7, 12, 95, 20])

In [178]:
np.dot(c,e)   ### dot product

9509