## Numpy:

In [1]:
### Installing the library:


In [2]:
pip install Numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
### Importing the library:

import numpy as np

### Creating the array:

In [4]:
## 1-d array:

a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [6]:
a.dtype    ### checking the array datatype.

dtype('int32')

In [12]:
a = np.array([1,2,3,4,'b'])
a

array(['1', '2', '3', '4', 'b'], dtype='<U11')

In [8]:
a.dtype

dtype('<U11')

In [13]:
a = np.append(a,10)   ### appending single element into the array.
a

array(['1', '2', '3', '4', 'b', '10'], dtype='<U11')

In [14]:
a = np.append(a,[20,30,40])   ### appending group of elements
a

array(['1', '2', '3', '4', 'b', '10', '20', '30', '40'], dtype='<U11')

In [11]:
a.dtype

dtype('<U11')

In [15]:
b = np.arange(1,11)   ### creating array of range of elements
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
b = np.arange(1,11,2)    ### range of elements with step values
b 

array([1, 3, 5, 7, 9])

In [20]:
b.nbytes   ### checking the memeory space occupied by array

20

In [24]:
b.itemsize   ### each element size

4

In [26]:
len(b)   ### total number elements in the array

5

In [28]:
a = np.linspace(1,10,20)   ### creating array with in the given range with required number of elements.
a

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [32]:
a = np.logspace(1,10,20)   ### creating the array within the given range with required number of elements with their log values.
a

array([1.00000000e+01, 2.97635144e+01, 8.85866790e+01, 2.63665090e+02,
       7.84759970e+02, 2.33572147e+03, 6.95192796e+03, 2.06913808e+04,
       6.15848211e+04, 1.83298071e+05, 5.45559478e+05, 1.62377674e+06,
       4.83293024e+06, 1.43844989e+07, 4.28133240e+07, 1.27427499e+08,
       3.79269019e+08, 1.12883789e+09, 3.35981829e+09, 1.00000000e+10])

In [33]:
np.full(10,"numpy")    ### repeating required number of times and making into array

array(['numpy', 'numpy', 'numpy', 'numpy', 'numpy', 'numpy', 'numpy',
       'numpy', 'numpy', 'numpy'], dtype='<U5')

In [36]:
np.full(10,"1 2")

array(['1 2', '1 2', '1 2', '1 2', '1 2', '1 2', '1 2', '1 2', '1 2',
       '1 2'], dtype='<U3')

In [39]:
np.ones(10,dtype = int)   ### repeating 1 for defined number of times.

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [42]:
np.zeros(10,dtype = int)   ### repeating 0  for defined number of times

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [51]:
#### 2-d array:   combination more number of 1-d arrays

a = np.array([[1,2,3,4],[5,6,7,8],[4,5,6,7]])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [4, 5, 6, 7]])

In [44]:
a.dtype

dtype('int32')

In [45]:
a.nbytes

32

In [46]:
a.itemsize

4

In [48]:
a.ndim    ### checking the dimension of the array

2

In [49]:
b.ndim

1

In [53]:
len(a)   ### number of rows

3

In [54]:
### 3-d array:   combination of more number of 2-d arrays.

a = np.array([[[1,2,3,4],[4,5,6,7]],[[9,8,7,6],[2,3,4,5]]])
a



array([[[1, 2, 3, 4],
        [4, 5, 6, 7]],

       [[9, 8, 7, 6],
        [2, 3, 4, 5]]])

In [55]:
a.ndim

3

In [56]:
len(a)

2

In [59]:
### mutli dimensional arrays:

a = np.array([1,2,3,4,5],ndmin = 20)
a

array([[[[[[[[[[[[[[[[[[[[1, 2, 3, 4, 5]]]]]]]]]]]]]]]]]]]])

In [60]:
a.ndim

20

### Acceessing the elements from the array:


In [63]:
### 1-d array:

a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [64]:
a[1]

2

In [65]:
a[-1]

6

In [66]:
a[-3]

4

In [67]:
a[1:4]

array([2, 3, 4])

In [68]:
a[-3:]

array([4, 5, 6])

In [69]:
a[-1::-1]

array([6, 5, 4, 3, 2, 1])

In [71]:
### 2-d array:

b = np.array([[1,2,3,4],[5,6,7,8]])
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [72]:
b[0]   ### row index

array([1, 2, 3, 4])

In [73]:
b[1]

array([5, 6, 7, 8])

In [74]:
b[0,2]   ### row index,element index

3

In [75]:
b[1,2]

7

In [76]:
b[:,-1]

array([4, 8])

In [78]:
b[:,-2:]   ### rowindex slicing,element index slicing

array([[3, 4],
       [7, 8]])

In [80]:
b[:,1:3]

array([[2, 3],
       [6, 7]])

In [81]:
b[1:3,1:3]

array([[6, 7]])

In [82]:
b[:,0::2]

array([[1, 3],
       [5, 7]])

In [83]:
b[:,1::2]

array([[2, 4],
       [6, 8]])

In [84]:
### 3-d array:

a = np.array([[[1,2,3,4],[4,5,6,7]],[[9,8,7,6],[2,3,4,5]]])
a


array([[[1, 2, 3, 4],
        [4, 5, 6, 7]],

       [[9, 8, 7, 6],
        [2, 3, 4, 5]]])

In [85]:
a[0]  ###  2-d index

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [86]:
a[1]

array([[9, 8, 7, 6],
       [2, 3, 4, 5]])

In [87]:
a[0,0]    ### 2-d index,row index

array([1, 2, 3, 4])

In [88]:
a[1,1]

array([2, 3, 4, 5])

In [90]:
a[1,1,-2]   ### 2-d index,row index,element index

4

In [91]:
a[:,0,-1]

array([4, 6])

In [92]:
a[:,0,1:3]

array([[2, 3],
       [8, 7]])

In [93]:
a[:,:,-1]

array([[4, 7],
       [6, 5]])

In [94]:
a[:,:,1:3]

array([[[2, 3],
        [5, 6]],

       [[8, 7],
        [3, 4]]])

###  shape of arrays:

In [95]:
### 1-d array:

a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [96]:
a.shape  ### number of elements

(4,)

In [97]:
### 2-d array:
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [98]:
b.shape   ### rows and columns

(2, 4)

In [99]:
### 3-d array:

c = np.array([[[1,2,3,4],[5,6,7,8]],[[5,6,7,8],[9,5,1,4]]])
c

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]],

       [[5, 6, 7, 8],
        [9, 5, 1, 4]]])

In [100]:
c.shape

(2, 2, 4)

In [101]:
a.size   ### getting the total number of elements in the array

4

In [102]:
b.size

8

In [103]:
c.size

16

### Reshaping of the array:

* giving a new shape to array.


In [105]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [106]:
a.size

20

In [107]:
b = a.reshape(4,5)
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [108]:
b.ndim

2

In [109]:
a.reshape(5,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [110]:
a.reshape(2,10)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [111]:
a.reshape(2,5,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]],

       [[11, 12],
        [13, 14],
        [15, 16],
        [17, 18],
        [19, 20]]])

In [112]:
a.reshape(5,2,2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16]],

       [[17, 18],
        [19, 20]]])

In [113]:
a.reshape(10,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20]])

In [114]:
a.reshape(4,-1)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [115]:
a.reshape(-1,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [116]:
a.reshape(-1,2,5)

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]]])

In [119]:
### arange function with different dimensions:

a = np.arange(1,11).reshape(5,2)
a

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [120]:
### Task :

### create arrays using numpy with all the data types available in the numpy library.